package cli

import (
	"encoding/json"
	"io"
	"os"
	"path/filepath"
	"strings"

	"yore/internal/rec"
)

// agentOpenCode is the executor tag stamped on commands captured from OpenCode.
const agentOpenCode = "opencode"

// opencodeHookInput is the JSON our OpenCode plugin pipes to the hook commands.
// Unlike Cursor/Claude this schema is ours (we author both the plugin and the
// handler), so the plugin adapts OpenCode's objects into these fields.
type opencodeHookInput struct {
	SessionID string `json:"session_id"`
	Command   string `json:"command"`
	Cwd       string `json:"cwd"`
	Exit      *int   `json:"exit"` // OpenCode provides output.metadata.exit
	Prompt    string `json:"prompt"`
}

func opencodeSession(id string) string {
	if id == "" {
		return ""
	}
	return "opencode-" + id
}

// runHookOpenCode records a command reported by the OpenCode plugin's
// tool.execute.after hook (tagged opencode, with exit status and prompt
// tracing). Silent no-op on empty command or malformed JSON; always exits 0.
func runHookOpenCode() {
	raw, err := io.ReadAll(io.LimitReader(os.Stdin, 1<<20))
	if err != nil {
		return
	}
	var in opencodeHookInput
	if json.Unmarshal(raw, &in) != nil {
		return
	}
	cmd := strings.TrimSpace(in.Command)
	if cmd == "" {
		return
	}
	dir := stateDir()
	session := opencodeSession(in.SessionID)
	r := rec.Record{
		Session:  session,
		Cmd:      cmd,
		Cwd:      in.Cwd,
		Executor: agentOpenCode,
		Exit:     in.Exit,
	}
	stampPrompt(dir, session, &r)
	spoolRecord(dir, r)
}

// runHookOpenCodePrompt records the session's current prompt from the OpenCode
// plugin's message hook, for the command hook to attach. It never blocks and
// never prints (the plugin fires it and forgets: it does not read our stdout).
func runHookOpenCodePrompt() {
	raw, err := io.ReadAll(io.LimitReader(os.Stdin, 1<<20))
	if err != nil {
		return
	}
	var in opencodeHookInput
	if json.Unmarshal(raw, &in) != nil {
		return
	}
	recordPrompt(stateDir(), opencodeSession(in.SessionID), agentOpenCode, in.Cwd, in.Prompt)
}

// --- `yore init opencode`: install the capture plugin -----------------------

// opencodePluginTemplate is the JS plugin OpenCode auto-loads. It adapts
// OpenCode's tool.execute.after and message events into yore hook calls,
// piping JSON on stdin. __YORE_BIN__ is replaced with the binary to invoke.
// Field access follows OpenCode's documented plugin API (tool.execute.after
// receives (toolInput, output): toolInput.tool/args.command/args.workdir/
// sessionID and output.metadata.exit; the event hook sees message.updated and
// message.part.updated).
const opencodePluginTemplate = `// yore: OpenCode capture plugin (generated by ` + "`yore init opencode`" + `)
// Records the commands OpenCode's agent runs into your yore history.
import { spawnSync } from "child_process";

const YORE = "__YORE_BIN__";
const userMessages = new Set();

function send(sub, payload) {
  try {
    spawnSync(YORE, ["hook", sub], {
      input: JSON.stringify(payload),
      stdio: ["pipe", "ignore", "ignore"],
      timeout: 5000,
    });
  } catch {}
}

export default async () => ({
  event: async (eventInput) => {
    const evt = eventInput?.event;
    if (!evt) return;
    if (evt.type === "message.updated") {
      const info = evt.properties?.info;
      if (info?.role === "user" && info?.id) userMessages.add(info.id);
      return;
    }
    if (evt.type === "message.part.updated") {
      const part = evt.properties?.part;
      if (part?.type === "text" && part?.text && part?.messageID && userMessages.has(part.messageID)) {
        userMessages.delete(part.messageID);
        send("opencode-prompt", { session_id: part.sessionID || "", prompt: part.text });
      }
    }
  },
  "tool.execute.after": async (toolInput, output) => {
    if (toolInput?.tool !== "bash") return;
    const command = toolInput.args?.command;
    if (!command) return;
    const payload = {
      session_id: toolInput.sessionID || "",
      command,
      cwd: toolInput.args?.workdir || process.cwd(),
    };
    const exit = output?.metadata?.exit;
    if (exit !== undefined && exit !== null) payload.exit = exit;
    send("opencode", payload);
  },
});
`

// opencodePluginScript renders the plugin for the given binary.
func opencodePluginScript(bin string) string {
	return strings.ReplaceAll(opencodePluginTemplate, "__YORE_BIN__", bin)
}

// opencodePluginPath resolves where OpenCode auto-loads plugins: the project
// .opencode/plugins/yore.js with --project, else ~/.config/opencode/plugins/yore.js.
func opencodePluginPath(project bool) (string, error) {
	if project {
		return filepath.Join(".opencode", "plugins", "yore.js"), nil
	}
	home, err := os.UserHomeDir()
	if err != nil {
		return "", err
	}
	return filepath.Join(home, ".config", "opencode", "plugins", "yore.js"), nil
}

// installOpenCodePlugin writes yore's capture plugin into OpenCode's plugins
// directory.
func installOpenCodePlugin(bin string, project bool, u *ui) error {
	path, err := opencodePluginPath(project)
	if err != nil {
		return err
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	if err := os.WriteFile(path, []byte(opencodePluginScript(bin)), 0o644); err != nil {
		return err
	}
	u.step("installed OpenCode capture plugin", path)
	return nil
}

// --- OpenCode MCP registration ----------------------------------------------

// opencodeConfigPath resolves OpenCode's config file: the project opencode.json
// with --project, else the user ~/.config/opencode/opencode.json.
func opencodeConfigPath(project bool) (string, error) {
	if project {
		return "opencode.json", nil
	}
	home, err := os.UserHomeDir()
	if err != nil {
		return "", err
	}
	return filepath.Join(home, ".config", "opencode", "opencode.json"), nil
}

// mergeOpenCodeMcp registers yore under the config's "mcp" map (a local stdio
// server) unless it is already there. Returns whether it changed anything.
func mergeOpenCodeMcp(cfg map[string]any, bin string) bool {
	mcp, _ := cfg["mcp"].(map[string]any)
	if mcp == nil {
		mcp = map[string]any{}
	}
	if _, ok := mcp["yore"]; ok {
		return false
	}
	mcp["yore"] = map[string]any{
		"type":    "local",
		"command": []any{bin, "mcp-serve"},
		"enabled": true,
	}
	cfg["mcp"] = mcp
	return true
}

// registerOpenCodeMcp merges yore's MCP server into OpenCode's config, preserving
// everything else. A malformed existing file is left alone.
func registerOpenCodeMcp(bin string, project bool, u *ui) error {
	path, err := opencodeConfigPath(project)
	if err != nil {
		return err
	}
	cfg := map[string]any{}
	if data, rerr := os.ReadFile(path); rerr == nil {
		if json.Unmarshal(data, &cfg) != nil {
			u.step("skipped MCP registration (existing opencode.json is not valid JSON)", path)
			return nil //nolint:nilerr // intentional: leave the unparseable file untouched
		}
	} else if !os.IsNotExist(rerr) {
		return rerr
	}
	if !mergeOpenCodeMcp(cfg, bin) {
		u.step("MCP server already registered", path)
		return nil
	}
	out, err := json.MarshalIndent(cfg, "", "  ")
	if err != nil {
		return err
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	if err := os.WriteFile(path, append(out, '\n'), 0o644); err != nil {
		return err
	}
	u.step("registered MCP server", path)
	return nil
}

// opencodeMcpRegistered reports whether yore's MCP server is in OpenCode's config.
func opencodeMcpRegistered() bool {
	path, err := opencodeConfigPath(false)
	if err != nil {
		return false
	}
	data, err := os.ReadFile(path)
	if err != nil {
		return false
	}
	var cfg map[string]any
	if json.Unmarshal(data, &cfg) != nil {
		return false
	}
	mcp, _ := cfg["mcp"].(map[string]any)
	_, ok := mcp["yore"]
	return ok
}

// opencodePluginInstalled reports whether yore's OpenCode plugin is present.
func opencodePluginInstalled() bool {
	path, err := opencodePluginPath(false)
	if err != nil {
		return false
	}
	_, err = os.Stat(path)
	return err == nil
}

// runInitOpenCode installs yore's OpenCode capture plugin so the commands its
// agent runs are recorded (tagged opencode, with exit status and prompt tracing).
func runInitOpenCode(bin string, project bool) int {
	u := newUI()
	u.title("yore init opencode")
	if err := installOpenCodePlugin(bin, project, u); err != nil {
		u.fail(err.Error())
		return 1
	}
	if err := registerOpenCodeMcp(bin, project, u); err != nil {
		u.step("could not register MCP server (capture still works)", err.Error())
	}
	u.step("captures every command OpenCode's agent runs", "tagged "+agentOpenCode+", traced to its prompt")
	u.step("OpenCode can also query your history via MCP", "cross-machine, end-to-end encrypted")
	u.blank()
	u.next("restart OpenCode, then see agent commands with:",
		"yore search --executor "+agentOpenCode,
		"hb   (browse)")
	return 0
}
