package cli

import (
	"encoding/json"
	"io"
	"os"
	"path/filepath"
	"strings"
	"time"

	"yore/internal/config"
	"yore/internal/rec"
	"yore/internal/redact"
)

// agentOpenCode is the executor tag stamped on commands captured from OpenCode.
const agentOpenCode = "opencode"

// opencodeHookInput is the JSON our OpenCode plugin pipes to the hook commands.
// Unlike Cursor/Claude this schema is ours (we author both the plugin and the
// handler), so the plugin adapts OpenCode's objects into these fields.
type opencodeHookInput struct {
	SessionID string `json:"session_id"`
	Command   string `json:"command"`
	Cwd       string `json:"cwd"`
	Exit      *int   `json:"exit"` // OpenCode provides output.metadata.exit
	Prompt    string `json:"prompt"`
}

func opencodeSession(id string) string {
	if id == "" {
		return ""
	}
	return "opencode-" + id
}

// runHookOpenCode records a command reported by the OpenCode plugin's
// tool.execute.after hook (tagged opencode, with exit status and prompt
// tracing). Silent no-op on empty command or malformed JSON; always exits 0.
func runHookOpenCode() {
	raw, err := io.ReadAll(io.LimitReader(os.Stdin, 1<<20))
	if err != nil {
		return
	}
	var in opencodeHookInput
	if json.Unmarshal(raw, &in) != nil {
		return
	}
	cmd := strings.TrimSpace(in.Command)
	if cmd == "" {
		return
	}
	dir := stateDir()
	session := opencodeSession(in.SessionID)
	r := rec.Record{
		Session: session,
		Cmd:     cmd,
		Cwd:     in.Cwd,
		Tag:     agentOpenCode,
		Exit:    in.Exit,
	}
	if ps, ok := loadPromptState(dir, session); ok {
		r.PromptID = ps.ID
		r.Prompt = ps.Text
	}
	spoolRecord(dir, r)
}

// runHookOpenCodePrompt records the session's current prompt from the OpenCode
// plugin's message hook, for the command hook to attach. It never blocks and
// never prints (the plugin fires it and forgets — it does not read our stdout).
func runHookOpenCodePrompt() {
	raw, err := io.ReadAll(io.LimitReader(os.Stdin, 1<<20))
	if err != nil {
		return
	}
	var in opencodeHookInput
	if json.Unmarshal(raw, &in) != nil {
		return
	}
	text := strings.TrimSpace(in.Prompt)
	session := opencodeSession(in.SessionID)
	if text == "" || session == "" {
		return
	}
	dir := stateDir()
	cfg, _ := config.Load(dir)
	if filter, _ := redact.Load(dir, cfg.IgnorePatterns, cfg.IgnoreDirs); filter.Sensitive(text) {
		return
	}
	ps := promptState{ID: rec.NewID(), Text: text, Ms: time.Now().UnixMilli()}
	b, err := json.Marshal(ps)
	if err != nil {
		return
	}
	path := promptStatePath(dir, session)
	if os.MkdirAll(filepath.Dir(path), 0o700) != nil {
		return
	}
	_ = os.WriteFile(path, b, 0o600)
}

// --- `yore init opencode`: install the capture plugin -----------------------

// opencodePluginTemplate is the JS plugin OpenCode auto-loads. It adapts
// OpenCode's tool.execute.after and message events into yore hook calls,
// piping JSON on stdin. __YORE_BIN__ is replaced with the binary to invoke.
// Field access follows OpenCode's documented plugin API (tool.execute.after
// receives (toolInput, output): toolInput.tool/args.command/args.workdir/
// sessionID and output.metadata.exit; the event hook sees message.updated and
// message.part.updated).
const opencodePluginTemplate = `// yore — OpenCode capture plugin (generated by ` + "`yore init opencode`" + `)
// Records the commands OpenCode's agent runs into your yore history.
import { spawnSync } from "child_process";

const YORE = "__YORE_BIN__";
const userMessages = new Set();

function send(sub, payload) {
  try {
    spawnSync(YORE, ["hook", sub], {
      input: JSON.stringify(payload),
      stdio: ["pipe", "ignore", "ignore"],
      timeout: 5000,
    });
  } catch {}
}

export default async () => ({
  event: async (eventInput) => {
    const evt = eventInput?.event;
    if (!evt) return;
    if (evt.type === "message.updated") {
      const info = evt.properties?.info;
      if (info?.role === "user" && info?.id) userMessages.add(info.id);
      return;
    }
    if (evt.type === "message.part.updated") {
      const part = evt.properties?.part;
      if (part?.type === "text" && part?.text && part?.messageID && userMessages.has(part.messageID)) {
        userMessages.delete(part.messageID);
        send("opencode-prompt", { session_id: part.sessionID || "", prompt: part.text });
      }
    }
  },
  "tool.execute.after": async (toolInput, output) => {
    if (toolInput?.tool !== "bash") return;
    const command = toolInput.args?.command;
    if (!command) return;
    const payload = {
      session_id: toolInput.sessionID || "",
      command,
      cwd: toolInput.args?.workdir || process.cwd(),
    };
    const exit = output?.metadata?.exit;
    if (exit !== undefined && exit !== null) payload.exit = exit;
    send("opencode", payload);
  },
});
`

// opencodePluginScript renders the plugin for the given binary.
func opencodePluginScript(bin string) string {
	return strings.ReplaceAll(opencodePluginTemplate, "__YORE_BIN__", bin)
}

// opencodePluginPath resolves where OpenCode auto-loads plugins: the project
// .opencode/plugins/yore.js with --project, else ~/.config/opencode/plugins/yore.js.
func opencodePluginPath(project bool) (string, error) {
	if project {
		return filepath.Join(".opencode", "plugins", "yore.js"), nil
	}
	home, err := os.UserHomeDir()
	if err != nil {
		return "", err
	}
	return filepath.Join(home, ".config", "opencode", "plugins", "yore.js"), nil
}

// installOpenCodePlugin writes yore's capture plugin into OpenCode's plugins
// directory.
func installOpenCodePlugin(bin string, project bool, u *ui) error {
	path, err := opencodePluginPath(project)
	if err != nil {
		return err
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	if err := os.WriteFile(path, []byte(opencodePluginScript(bin)), 0o644); err != nil {
		return err
	}
	u.step("installed OpenCode capture plugin", path)
	return nil
}

// opencodePluginInstalled reports whether yore's OpenCode plugin is present.
func opencodePluginInstalled() bool {
	path, err := opencodePluginPath(false)
	if err != nil {
		return false
	}
	_, err = os.Stat(path)
	return err == nil
}

// runInitOpenCode installs yore's OpenCode capture plugin so the commands its
// agent runs are recorded (tagged opencode, with exit status and prompt tracing).
func runInitOpenCode(bin string, project bool) int {
	u := newUI()
	u.title("yore init opencode")
	if err := installOpenCodePlugin(bin, project, u); err != nil {
		u.fail(err.Error())
		return 1
	}
	u.step("captures every command OpenCode's agent runs", "tagged "+agentOpenCode+", traced to its prompt")
	u.blank()
	u.next("restart OpenCode, then see agent commands with:",
		"yore search --executor "+agentOpenCode,
		"hb   (browse)")
	return 0
}
